language: scala

scala:
  - 2.12.8

jdk:
  - openjdk11

stages:
  - name: test
  - name: release
  - name: mutation testing
    if: type = cron

jobs:
  include:
    - name: Test frontend
      stage: test
      script:
      - cd frontend
      - npm ci
      - npm test
    - name: Test backend
      stage: test
      script: 
      - cd backend
      - sbt ++$TRAVIS_SCALA_VERSION test
    - name: Test formatting (backend)
      stage: test
      script:
      - cd backend
      - ./bin/scalafmt --test
    - stage: mutation testing
      name: Stryker
      script: 
      - cd frontend
      - npm ci
      - npm run stryker
    - stage: mutation testing
      name: Stryker4s
      script: 
      - cd backend 
      - sbt stryker
    - name: release
      stage: release
      script:
      - echo "WIP"

before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" -print -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete

cache:
  npm: true
  # These directories are cached to S3 at the end of the build
  directories:
    - $HOME/.sbt
    - $HOME/.ivy2/cache
    - $HOME/.cache/coursier
