openapi: "3.0.0"
info:
  title: Compass API
  version: 0.0.1
paths:
  /api/providers/series:
    get:
      operationId: getSeries
      summary: Returns all series
      responses:
        200:
          description: Hello message
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SeriesResponse'
components:
  schemas:
    SeriesResponse:
      type: object
      properties:
        name:
          type: string
      required:
        - name
