addSbtPlugin("io.spray"           % "sbt-revolver"        % "0.9.1")
addSbtPlugin("com.twilio"         % "sbt-guardrail"       % "0.54.5")
addSbtPlugin("io.stryker-mutator" % "sbt-stryker4s"       % "0.6.1")
addSbtPlugin("com.geirsson"       % "sbt-ci-release"      % "1.4.31")
addSbtPlugin("com.typesafe.sbt"   % "sbt-native-packager" % "1.5.1")
