name: Publish GitHub pages

on:
  push:
    branches:
      - master

jobs:
  publish-gh-pages:
    name: Publish GitHub pages
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: olafurpg/setup-scala@v5
        with:
          java-version: "openjdk@1.11"
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: "2.x"
      - name: Install Ruby dependencies
        run: |
          gem install sassc
          gem install jekyll -v 4.0.0
      - name: Publish GitHub pages
        run: |
          cd backend
          csbt docs/publishMicrosite
        env:
          GH_PAGES_DEPLOY_TOKEN: ${{ secrets.GH_PAGES_DEPLOY_TOKEN }}
