name: Mutation testing

on:
  push:
    branches:
      - master

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Run Stryker
        run: |
          cd frontend
          npm ci
          npm run stryker
        env:
          STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}
      - name: Upload HTML report artifact
        uses: actions/upload-artifacts@v1
        with:
          name: 'frontend-html-report'
          path: 'frontend/reports/mutation/html'

  backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: olafurpg/setup-scala@v5
        with:
          java-version: 'openjdk@1.11'
      - name: Run Stryker4s
        run: |
          cd backend
          csbt stryker
        env:
          STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}
      - name: Upload HTML report artifact
        uses: actions/upload-artifacts@v1
        with:
          name: 'backend-html-report'
          path: 'backend/target/stryker4s-report-*'
